package com.example.intro.menu;

import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.GridLayout;
import android.widget.LinearLayout;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.content.ContextCompat;
import androidx.fragment.app.Fragment;

import com.example.intro.MainActivity;
import com.example.intro.R;
import com.example.intro.firebase.RecipeList;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

// 검색 기능
public class FragmentPage1 extends Fragment {
    private List<String> list;

    //태그내용 저장하는 리스트 생성. 크기는 5
    ArrayList<String> taglist = new ArrayList<String>(5);

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        //setHasOptionsMenu(true);

        //프래그먼트에서 findBiewById 사용하려면 먼저 선언해 줘야함
        View v = inflater.inflate(R.layout.fragment_page_1, container, false);

        list = new ArrayList<String>(); //자동완성 검색 내용을 담을 리스트 생성
        settingList();

        final AutoCompleteTextView autoCompleteTextView = (AutoCompleteTextView)v.findViewById((R.id.autoCompleteTextView33));
        //자동완성 검색창 어댑터
        autoCompleteTextView.setAdapter(new ArrayAdapter<String>(getContext(), android.R.layout.simple_dropdown_item_1line, list));

        //검색창 엔터키 이벤트
        autoCompleteTextView.setOnKeyListener(new View.OnKeyListener() {
            @Override
            public boolean onKey(View view, int keycode, KeyEvent keyEvent) {
                //키보드 상에서 엔터키 입력받음
                if(keyEvent.getAction() == KeyEvent.ACTION_DOWN && keycode == KeyEvent.KEYCODE_ENTER){
                    //엔터키 이벤트 동작확인 토스트 메시지
                    // Toast.makeText(getActivity().getApplicationContext(), "태그 생성", Toast.LENGTH_SHORT).show();

                    //버튼추가 함수에 넘겨줄 문자열. 검색창 내용을 복사
                    String a1 = autoCompleteTextView.getText().toString();

                    addButton(a1);  //버튼추가 함수. 문자열 a1을 인자로 넘겨줌
                    autoCompleteTextView.setText("");
                    return true;    //엔터키로 줄바꿈 방지

                }
                return false;
            }
        });
        return v;   //반드시 v를 리턴
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
    }

    //버튼추가 함수
    public void addButton(String a1){
        //태그내용 추가
        taglist.add(a1);

        //버튼 동적 생성
        GridLayout manager = (GridLayout)getView().findViewById(R.id.glayout33);
        Button btn = new Button(getContext());
        btn.setText("#" + a1);
        btn.setBackground(ContextCompat.getDrawable(getActivity(), R.drawable.buttonbackground));
        //생성되는 버튼의 크기 설정
        btn.setLayoutParams(new LinearLayout.LayoutParams(220,120));
        //버튼 안의 텍스트 크기 설정
        btn.setTextSize(15);
        manager.addView(btn);

        //버튼클릭 이벤트. 삭제용
        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //버튼 삭제. 안보이고 공간을 차지하지 않음
                btn.setVisibility(View.GONE);
                btn.setEnabled(false);

                //태그내용 삭제
                taglist.remove(a1);
            }
        });

        //태그완성 버튼 클릭 이벤트
        Button tbutton = (Button)getView().findViewById(R.id.tbutton);

        tbutton.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View view) {
                //배열 출력
                String list = Arrays.toString(taglist.toArray()).replace("[", "").replace("]", "")
                        .replace(",", "").replace("\n", "");
                System.out.println(list);
                Intent intent = new Intent(getActivity(), RecipeList.class);
                intent.putExtra("taglist", list);
                startActivity(intent);
                //인텐트는 에러발생

                //Fragment fragment = new Fragment();
                //Bundle bundle = new Bundle();
                //bundle.putStringArrayList("taglist", taglist);
                //fragment.setArguments(bundle);
                //배열 데이터 전달. 확인필요
            }
        });

    }

    //자동완성으로 보이게 할 단어들 목록
    private void settingList() {
        list.add("청경채");
        list.add("부추");
        list.add("새우");
        list.add("버섯");
        list.add("양파");
        list.add("다진마늘");
        list.add("청양고추");
        list.add("식용유");
        list.add("굴소스");
        list.add("간장");
        list.add("참기름");
        list.add("소금");
        list.add("후추");
        list.add("전분가루");
        list.add("물");
        list.add("굴비");
        list.add("시래기");
        list.add("대파");
        list.add("생강");
        list.add("다시물");
        list.add("된장");
        list.add("국간장");
        list.add("고춧가루");
        list.add("매실청");
        list.add("들기름");
        list.add("참마면 칼국수");
        list.add("콩나물");
        list.add("당근채");
        list.add("청상추");
        list.add("양파채");
        list.add("치커리");
        list.add("김가루");
        list.add("고추장");
        list.add("진간장");
        list.add("식초(레몬)");
        list.add("설탕");
        list.add("통깨");
        list.add("파채");
        list.add("대패삼겹살");
        list.add("식초");
        list.add("닭");
        list.add("소주");
        list.add("쌀가루");
        list.add("치킨튀김가루");
        list.add("청주");
        list.add("맛술");
        list.add("꿀");
        list.add("마늘");
        list.add("우렁이살");
        list.add("감자");
        list.add("애호박");
        list.add("두부");
        list.add("팽이버섯");
        list.add("마른표고버섯");
        list.add("다시멸치");
        list.add("고추가루");
        list.add("닭봉");
        list.add("우유");
        list.add("마늘가루");
        list.add("허브솔트");
        list.add("오일");
        list.add("꽈리고추");
        list.add("어묵");
        list.add("당근");
        list.add("식초(산야초효소)");
        list.add("버터");
        list.add("땅콩 피넛 버터");
        list.add("황설탕");
        list.add("달걀");
        list.add("박력분");
        list.add("베이킹 파우더");
        list.add("베이킹 소다");
        list.add("무염버터");
        list.add("흑설탕");
        list.add("중력분");
        list.add("생강가루");
        list.add("베이킹파우더");
        list.add("베이킹소다");
        list.add("레몬즙");
        list.add("생강 액");
        list.add("슈가파우더");
        list.add("오징어실채");
        list.add("올리고당");
        list.add("LA갈비");
        list.add("양념장");
        list.add("다진 마늘");
        list.add("생수");
        list.add("흑후추");
        list.add("키위");
        list.add("배");
        list.add("물엿");
        list.add("김");
        list.add("피망");
        list.add("계란");
        list.add("단무지");
        list.add("밥");
        list.add("다진대파");
        list.add("미림");
        list.add("떡");
        list.add("오뎅");
        list.add("파스타면");
        list.add("양배추");
        list.add("생크림");
        list.add("목이버섯");
        list.add("빨강파프리카");
        list.add("노랑파프리카");
        list.add("생새우");
        list.add("다진파");
        list.add("새우젓");
        list.add("참깨");
        list.add("소고기");
        list.add("고명 계란");
        list.add("다시다");
        list.add("번데기 통조림");
        list.add("소시지(편의점핫바)");
        list.add("달걀(전란)");
        list.add("바닐라익스트랙");
        list.add("마스카포네치즈");
        list.add("에스프레소 또는 원두커피");
        list.add("초코파우더");
        list.add("식빵");
        list.add("파");
        list.add("칠리소스");
        list.add("닭(9~10호)");
        list.add("냉동 돈까스");
        list.add("시금치");
        list.add("도루묵");
        list.add("청양고추나 홍고추");
        list.add("생강술 똔느 소주");
        list.add("무말랭이");
        list.add("건고추 잎");
        list.add("쪽파");
        list.add("다진생강");
        list.add("쌀엿");
        list.add("멸치액젓");
        list.add("고운고추가루");
        list.add("깨소금");
        list.add("곶감");
        list.add("스팸");
        list.add("꽃게");
        list.add("사과");
        list.add("조청");
        list.add("생강청");
        list.add("베이컨");
        list.add("체다치즈");
        list.add("마요네즈");
        list.add("핫소스");
        list.add("연유");
        list.add("파슬리가루");
        list.add("냉동감자");
        list.add("누른 오트밀");
        list.add("순두부");
        list.add("치킨스톡");
        list.add("피쉬소스");
        list.add("우엉(손질후)");
        list.add("굵은소금");
        list.add("노추 간장");
        list.add("홍피망");
        list.add("청피망");
        list.add("황 물엿");
        list.add("생강즙");
        list.add("떡국떡");
        list.add("김치왕만두");
        list.add("양지머리");
        list.add("간마늘");
        list.add("후춧가루");
        list.add("맛소금");
        list.add("카놀라유");
        list.add("섬초 시금치");
        list.add("매실액");
        list.add("자른대파");
        list.add("다시육수 팩");
        list.add("황태채");
        list.add("다진 쇠고기");
        list.add("풋고추");
        list.add("밀가루");
        list.add("녹말가루");
        list.add("생강술");
        list.add("연근");
        list.add("아가베시럽");
        list.add("견과류");
        list.add("미역");
        list.add("들깨가루");
        list.add("소금(죽염)");
        list.add("멸치다시마육수");
        list.add("김치(자르지않은)");
        list.add("채 썬 양파");
        list.add("깨");
        list.add("구운 김밥용 김");
        list.add("깻잎");
        list.add("김밥용 단무지");
        list.add("오징어젓(낙지젓 등 씨앗젓갈)");
        list.add("익은배추김치");
        list.add("간돼지고기");
        list.add("양파 약");
        list.add("고운고춧가루");
        list.add("꽃소금");
        list.add("딸기");
        list.add("양상치");
        list.add("어린잎채소");
        list.add("부라타 치즈");
        list.add("블랙올리브");
        list.add("발사믹소스 발사믹소스: 발사믹식초");
        list.add("올리브오일");
        list.add("쥐포");
        list.add("청량고추");
        list.add("홍고추");
        list.add("냉동만두 작은");
        list.add("모짜렐라치즈");
        list.add("또띠아");
        list.add("알배기배추");
        list.add("까나리액젓");
        list.add("머스타드소스(핫도그랠리쉬)");
        list.add("도미(매운탕용 생선)");
        list.add("무우");
        list.add("돼지고기(남은족발)");
        list.add("고추");
        list.add("양념장(양념치킨소스)");
        list.add("연어");
        list.add("올리브유");
        list.add("빵가루");
        list.add("파마산치즈가루");
        list.add("녹인버터");
        list.add("플레인요거트");
        list.add("다진양파");
        list.add("다시마 간장");
        list.add("액젓");
        list.add("꼬막");
        list.add("달래");
        list.add("소갈비 찜용");
        list.add("표고버섯");
        list.add("깐밤");
        list.add("파인애플통조림");
        list.add("두부 면");
        list.add("슬라이스마늘");
        list.add("양송이");
        list.add("휘핑크림");
        list.add("후추가루");
        list.add("레드페퍼");
        list.add("파마산치즈");
        list.add("닭가슴살");
        list.add("요거트");
        list.add("디종머스타드");
        list.add("샐러리");
        list.add("피칸");
        list.add("건크랜베리");
        list.add("파프리카");
        list.add("빵");
        list.add("대창");
        list.add("페퍼론치노");
        list.add("알배추");
        list.add("쯔유");
        list.add("유부 초밥 세트(시판용)");
        list.add("맛살");
        list.add("조린 우엉");
        list.add("소불고기 거리");
        list.add("통밀식빵");
        list.add("허니머스타드소스(유기농)");
        list.add("자색양파");
        list.add("삶은계란");
        list.add("아보카도");
        list.add("다시육수");
        list.add("갈색설탕");
        list.add("레몬");
        list.add("계핏가루");
        list.add("닭가슴살(무항생제)");
        list.add("굴소스(유기농)");
        list.add("한식간장");
        list.add("비정제설탕");
        list.add("기름(현미)");
        list.add("남은치킨");
        list.add("소고기 약");
        list.add("미향");
        list.add("케첩");
        list.add("돼지고기");
        list.add("김치");
        list.add("통마늘");
        list.add("풋마늘");
        list.add("참치액");
        list.add("매실");
        list.add("톳");
        list.add("콜라비");
        list.add("고추장(찹쌀)");
        list.add("현미식초");
        list.add("매실 효소");
        list.add("낙지");
        list.add("청양고추 다진거");
        list.add("돼지등뼈");
        list.add("월계수잎");
        list.add("브로콜리 자른것");
        list.add("굴");
        list.add("어린잎새싹");
        list.add("춘장(짜장가루)");
        list.add("당면");
        list.add("오리고기");
        list.add("파래");
        list.add("무(작은것)");
        list.add("배 간것");
        list.add("해물 육수");
        list.add("고구마");
        list.add("쌀밥");
        list.add("간 파프리카");
        list.add("아기 된장");
        list.add("아기 간장");
        list.add("사과즙");
        list.add("양송이버섯");
        list.add("미니파프리카");
        list.add("바닐라오일");
        list.add("흰자");
        list.add("노른자");
        list.add("유정란");
        list.add("소고기 다짐육");
        list.add("방울토마토");
        list.add("우유(킨더밀쉬)");
        list.add("아기 치즈");
        list.add("모시조개");
        list.add("느타리버섯");
        list.add("배추잎");
        list.add("미나리");
        list.add("봄동");
        list.add("마라 소스");
        list.add("닭(영계)");
        list.add("누룽지");
        list.add("황기 등(한약재)");
        list.add("동태");
        list.add("조림간장");
        list.add("신라면 작은컵");
        list.add("비엔나");
        list.add("라면스프");
        list.add("부침가루");
        list.add("무 즙");
        list.add("굵은 소금");
        list.add("무");
        list.add("강력분");
        list.add("드라이이스트");
        list.add("옥수수");
        list.add("소세지");
        list.add("허니머스타드");
        list.add("케찹");
        list.add("우엉");
        list.add("분말 한천");
        list.add("백앙금");
        list.add("말차가루");
        list.add("따뜻한 물");
        list.add("떡볶이 떡");
        list.add("파마산 치즈가루");
        list.add("곱창 전골 밀키트");
        list.add("천연조미료육수");
        list.add("소불고기");
        list.add("떡 쌈");
        list.add("양념장(숯불향고기소스)");
        list.add("튀김가루");
        list.add("오징어");
        list.add("육수");
        list.add("김밥김");
        list.add("대파흰부분");
        list.add("CJ 가쓰오 우동");
        list.add("아무 버섯");
        list.add("송송 썬파");
        list.add("통밀또띠아");
        list.add("수제 토마토소스");
        list.add("자연 스트링치즈");
        list.add("다시용멸치");
        list.add("된장(집된장+다담된장찌개된장)");
        list.add("밥 고구마 큰거");
        list.add("흑임자 가루");
        list.add("귤");
        list.add("배추");
        list.add("천일염 반");
        list.add("멸치 액젓");
        list.add("생강 즙");
        list.add("고구마(중간 것)");
        list.add("사과(갈아서 얼린 것)");
        list.add("삼겹살 수육");
        list.add("다시마육수");
        list.add("생강(말린 것)");
        list.add("로즈마리");
        list.add("옥수수 캔");
        list.add("모짜렐라 치즈");
        list.add("무가당 코코아 파우더");
        list.add("팥앙금");
        list.add("비정제 설탕");
        list.add("양상추");
        list.add("적채");
        list.add("로메인");
        list.add("슬라이스아몬드");
        list.add("건블루베리");
        list.add("떡(떡볶이용)");
        list.add("초고추장");
        list.add("새송이버섯");
        list.add("토마토스파게티소스");
        list.add("스파게티면");
        list.add("칵테일새우");
        list.add("토마토");
        list.add("브로콜리");
        list.add("캔옥수수");
        list.add("냉동 무뼈 닭발");
        list.add("베트남고추");
        list.add("치킨 가루");
        list.add("카레가루");
        list.add("허니 갈릭 치킨소스");
        list.add("매운 양념 치킨 소스");
        list.add("두반장");
        list.add("고추기름");
        list.add("떡갈비");
        list.add("슬라이스치즈");
        list.add("볶은 김치");
        list.add("밥(1팩)");
        list.add("견과류 멸치볶음");
        list.add("돈까스소스");
        list.add("유기농 블루베리");
        list.add("2배 식초");
        list.add("토마토케첩");
        list.add("연어 뱃살");
        list.add("갈은깨");
        list.add("간장 소스");
        list.add("사각어묵");
        list.add("해물 육수팩");
        list.add("스파게티소스");
        list.add("치킨육수");
        list.add("매운고추");
        list.add("묵은지");
        list.add("멸치다시육수");
        list.add("쫄면");
        list.add("오이");
        list.add("돼지고기앞다리 불고기용");
        list.add("항정살");
        list.add("검은깨");
        list.add("빵(크로와상)");
        list.add("햄");
        list.add("루꼴라");
        list.add("크림치즈");
        list.add("어니언드레싱");
        list.add("양조간장");
        list.add("달걀노른자");
        list.add("스위트콘");
        list.add("크림 스파게티소스");
        list.add("한돈 뒷다리살");
        list.add("건새우");
        list.add("동태포");
        list.add("기름");
        list.add("돼지고기 채");
        list.add("국수면");
        list.add("마른고추");
        list.add("미원");
        list.add("대파채");
        list.add("깐마늘");
        list.add("맛간장");
        list.add("시금치(나물)");
        list.add("상추");
        list.add("사과식초");
        list.add("곱게 다진깨");
        list.add("순대");
        list.add("만두피");
        list.add("슈거파우더");
        list.add("편마늘");
        list.add("고체 카레");
        list.add("바닐라향");
        list.add("포항초");
        list.add("건다시마 작은크기");
        list.add("우리쌀 미소된장");
        list.add("치즈");
        list.add("게맛살");
        list.add("머스타드");
        list.add("사우전아일랜드 드레싱");
        list.add("고운소금");
        list.add("부침가루(메밀)");
        list.add("해바라기유");
        list.add("냉동 치킨");
        list.add("페페론치노");
        list.add("단호박");
        list.add("통조림햄");
        list.add("슬라이스 치즈");
        list.add("땅콩버터");
        list.add("딸기잼");
        list.add("시리얼");
        list.add("통 새우 튀김(피코크 후라이)");
        list.add("채 썬 양배추");
        list.add("레몬주스");
        list.add("3분 카레");
        list.add("소고기 치마살");
        list.add("토마토소스");
        list.add("감자 튀김(피코크 케이준 프라이)");
        list.add("다시마");
        list.add("가쓰오부시");
        list.add("3분 짜장");
        list.add("돼지고기 등심");
        list.add("모듬해물");
        list.add("꼬막 통조림");
        list.add("만두");
        list.add("삼겹살");
        list.add("감자전분");
        list.add("돼지목살");
        list.add("쌈장");
        list.add("호떡믹스");
        list.add("고구마샐러드");
        list.add("떡국용 떡");
        list.add("명란");
        list.add("멸치다시 육수팩");
        list.add("꽁치 통조림");
        list.add("라면(멸치칼국수면)");
        list.add("바지락");
        list.add("열빙어");
        list.add("즉석밥");
        list.add("닭고기");
        list.add("쌀뜨물");
        list.add("대구");
        list.add("홍초");
        list.add("월남고추");
        list.add("총각김치");
        list.add("게살(홍게살)");
        list.add("닭 가슴살");
        list.add("파프리카 가루");
        list.add("케이엔페퍼");
        list.add("고운 고춧가루");
        list.add("밀가루 또는 튀김가루");
        list.add("빵 가루");
        list.add("바질가루");
        list.add("청양 고춧가루");
        list.add("큐브 닭가슴살");
        list.add("아몬드 슬라이스");
        list.add("조랭이떡");
        list.add("네모 어묵");
        list.add("돼지앞다리살");
        list.add("양파(필수)");
        list.add("대파(필수)");
        list.add("당근(대체 및 생략가능)");
        list.add("버섯(대체 및 생략가능)");
        list.add("깻잎(대체 및 생략가능)");
        list.add("양배추(대체 및 생략가능)");
        list.add("청양고추(대체 및 생략가능)");
        list.add("건조 매생이");
        list.add("생굴");
        list.add("멸치");
        list.add("멸치액젓(까나리)");
        list.add("감자 또는 고구마");
        list.add("고구마줄기(삶은후)");
        list.add("다진돼지고기");
        list.add("번데기통조림(작은거)");
        list.add("요리당");
        list.add("모짜렐라");
        list.add("토마토 소스");
        list.add("돼지고기목심");
        list.add("진미채");
        list.add("매생이");
        list.add("떡국 떡");
        list.add("조미료(스프)");
        list.add("멸치육수");
        list.add("계란지단");
        list.add("짜장분말");
        list.add("완두콩");
        list.add("우둔살");
        list.add("밑간용 맛소금");
        list.add("흰후추");
        list.add("찹쌀가루");
        list.add("들깨");
        list.add("골뱅이");
        list.add("골뱅이 국물");
        list.add("소고기 불고기감");
        list.add("스팸 중간크기");
        list.add("소주 또는 맛술");
        list.add("김밥햄");
        list.add("참치캔");
        list.add("머스타드소스");
        list.add("한우사골");
        list.add("한우 잡뼈");
        list.add("소고기 양지");
        list.add("물(뼈양의)");
        list.add("할라피뇨 고추");
        list.add("적 파프리카");
        list.add("무(시중에 파는 절임)");
        list.add("겨자(소스)");
        list.add("불린 쌀");
        list.add("말린 톳");
        list.add("문어다리");
        list.add("소갈비");
        list.add("대추");
        list.add("황기");
        list.add("다시마 손바닥크기");
        list.add("호박");
        list.add("고형카레");
        list.add("돈가스");
        list.add("전분물");
        list.add("문어 다리");
        list.add("다진 청양고추");
        list.add("겨자");
        list.add("다진 소고기");
        list.add("슬라이스햄");
        list.add("잉글리쉬머핀");
        list.add("햄버거패티");
        list.add("쭈꾸미");
        list.add("당근 슬라이스");
        list.add("더덕");
        list.add("냉동 파인애플");
        list.add("계피가루");
        list.add("하몽");
        list.add("생모짜렐라치즈");
        list.add("천일염");
        list.add("묽은 찹쌀 죽");
        list.add("빵(꽃빵)");
        list.add("죽순");
        list.add("백태(대두콩)");
        list.add("콩비지");
        list.add("신김치");
        list.add("김치국물");
        list.add("매생이(동결건조)");
        list.add("튀김기름");
        list.add("피자치즈");
        list.add("돼지고기등심");
        list.add("카레");
        list.add("돼지고기안심");
        list.add("브로컬리");
        list.add("배즙");
        list.add("아욱");
        list.add("보리새우");
        list.add("방울 토마토");
        list.add("올리브오일 Olive oil");
        list.add("황설탕 Brown sugar");
        list.add("파슬리 Parsley");
        list.add("간장 Soy sauce");
        list.add("소금 Salt");
        list.add("간마늘 minced garlic");
        list.add("오렌지제스트 Orange zest");
        list.add("양념장(비법 소스)");
        list.add("2배식초");
        list.add("미역줄기");
        list.add("삶은 고구마줄기");
        list.add("당근(5cm길이)");
        list.add("3배 식초");
        list.add("사과즙(사과)");
        list.add("튀김가루(밀가루)");
        list.add("파래김");
        list.add("게간장");
        list.add("건 두부");
        list.add("숙주");
        list.add("깐새우");
        list.add("돼지고기앞다리살");
        list.add("간 돼지고기");
        list.add("양파(채)");
        list.add("레시피마다달라요!");
        list.add("날콩가루");
        list.add("멸치 채소 육수");
        list.add("콩가루");
        list.add("통밀가루");
        list.add("아몬드 가루");
        list.add("코코아파우더");
        list.add("코코넛 오일");
        list.add("머스코바도 설탕");
        list.add("호두");
        list.add("슬라이스 아몬드");
        list.add("돼지고기간것");
        list.add("작은 고구마");
        list.add("아몬드");
        list.add("무항생제 닭가슴살");
        list.add("숙주나물");
        list.add("미니새송이버섯");
        list.add("가지");
        list.add("잡곡 밥");
        list.add("차돌박이");
        list.add("주황파프리카");
        list.add("라면(사리곰탕)");
        list.add("미소된장");
        list.add("자숙문어");
        list.add("물(문어 삶은)");
        list.add("청양초");
        list.add("다용도 밀가루");
        list.add("두유나 우유");
        list.add("녹인 무염버터");
        list.add("바닐라 익스트렉");
        list.add("럼이나 맥주");
        list.add("닭다리살");
        list.add("유부");
        list.add("다시 육수");
        list.add("김밥용김");
        list.add("콩기름");
        list.add("판형 곤약");
        list.add("표고버섯 기둥(믈에 불려놓은)");
        list.add("마늘 작은거");
        list.add("북어");
        list.add("찌개용 두부");
        list.add("솔잎");
        list.add("담금 소주");
        list.add("소면");
        list.add("냉동 새우살");
        list.add("바게뜨빵");
        list.add("으깬통깨");
        list.add("무 radish");
        list.add("마늘 garlic");
        list.add("파 scallion");
        list.add("생강 ginger");
        list.add("빵(햄버거)");
        list.add("상추(양상추)");
        list.add("돼지고기 다짐육");
        list.add("소고기다짐육");
        list.add("디종 머스터드");
        list.add("파프리카 파우더");
        list.add("다진피클");
        list.add("스리라차소스");
        list.add("감");
        list.add("비엔나소세지");
        list.add("옥수수통조림");
        list.add("건포도");
        list.add("재래 김");
        list.add("찐 감자 작은것");
        list.add("크래미");
        list.add("홀그레인 머스터드");
        list.add("무뼈닭발");
        list.add("청양고추가루");
        list.add("소고기다시다");
        list.add("도라지");
        list.add("달걀흰자");
        list.add("아몬드가루");
        list.add("당절임콩");
        list.add("시나몬파우더");
        list.add("바나나");
        list.add("발사믹크림");
        list.add("양파 샐러드");
        list.add("연시");
        list.add("감식초");
        list.add("해바라기씨");
        list.add("생물국산 쭈꾸미");
        list.add("천연조미료 황태육수");
        list.add("모둠채소");
        list.add("치아바타");
        list.add("당근(라페)");
        list.add("홀그레인머스타드");
        list.add("레몬즙 또는 식초");
        list.add("홀그레인 머스타드");
        list.add("등갈비(10쪽)");
        list.add("닭다리(닭북채)");
        list.add("떡볶이떡");
        list.add("라면(스낵면사리)");
        list.add("불닭 볶음소스");
        list.add("옥수수 통조림");
        list.add("다진당근");
        list.add("파래 김");
        list.add("따뜻한물");
        list.add("잡채");
        list.add("피자소스");
        list.add("따뜻한 생크림");
        list.add("캐러멜소스");
        list.add("바닐라 익스트랙");
        list.add("익은김치");
        list.add("고등어통조림");
        list.add("포도씨유");
        list.add("소시지");
        list.add("생크림 또는 우유");
        list.add("생표고버섯");
        list.add("흰쌀");
        list.add("김밥용 김");
        list.add("손질 오징어");
        list.add("배춧잎");
        list.add("송송 썬 대파");
        list.add("샐러드야채");
        list.add("피넛버터");
        list.add("라임");
        list.add("스트링치즈");
        list.add("파르메산치즈");
        list.add("돼지 앞다리살");
        list.add("국수면(냉동 라멘면)");
        list.add("하오츠 훠궈 백탕");
        list.add("미소");
        list.add("반숙 계란");
        list.add("돼지고기(차슈 또는 수육)");
        list.add("물미역");
        list.add("참깨 또는 검은깨");
        list.add("고추 장아찌");
        list.add("냉동새우");
        list.add("다진 대파");
        list.add("수삼");
        list.add("잣");
        list.add("떡국 떡(현미)");
        list.add("간장(한식국산콩)");
        list.add("유기농 굴소스");
        list.add("무항생제 돼지고기");
        list.add("훠궈 마라탕 소스");
        list.add("알배추 잎");
        list.add("돼지앞다리살(얇게 자른것)");
        list.add("팽이버섯(작은)");
        list.add("소고기갈비 뼈");
        list.add("버섯 기둥");
        list.add("명란젓");
        list.add("참치캔(작은것)");
        list.add("스파게티소스(매콤한맛)");
        list.add("블랙올리브 절임");
        list.add("통조림파인애플");
        list.add("냉이");
        list.add("사골 곰국");
        list.add("닭다리살 정육");
        list.add("양파즙");
        list.add("버터(미니버터)");
        list.add("데리야끼소스");
        list.add("육수 또는 물");
        list.add("돼지고기삼겹살 또는 앞다리살");
        list.add("파뿌리");
        list.add("짜파게티");
        list.add("부라타치즈");
        list.add("아몬드슬라이스");
        list.add("발사믹식초");
        list.add("하림 손수만든 안심튀김");
        list.add("적 상추");
        list.add("어린잎 새싹채소");
        list.add("빨강 파프리카");
        list.add("노랑 파프리카");
        list.add("블랙 올리브");
        list.add("허니머스터드");
        list.add("스위트칠리소스");
        list.add("무(중간크기)");
        list.add("간양파");
        list.add("간 사과");
        list.add("사이다");
        list.add("체다 슬라이스치즈");
        list.add("천연조미료(톡톡채소 더맛국물요리&대파레시피)");
        list.add("흰밥");
        list.add("밥이랑 치즈");
        list.add("어묵(네모)");
        list.add("어묵(색깔)");
        list.add("우동사리");
        list.add("배추김치");
        list.add("쑥갓");
        list.add("또띠아 또는 피자생지");
        list.add("불고기");
        list.add("야채");
        list.add("청주나 맛술");
        list.add("생수(갈떄+소스만들떄)");
        list.add("부침가루(밀가루)");
        list.add("표고버섯 가루");
        list.add("건새우 가루");
        list.add("조개");
        list.add("미역(데친 곰피)");
        list.add("소고기홍두깨살");
        list.add("관자");
        list.add("마늘종");
        list.add("닭다리");
        list.add("피시소스");
        list.add("정종");
        list.add("스테이크용 소고기");
        list.add("홍합");
        list.add("화이트와인 또는 청주");
        list.add("건고추");
        list.add("쌀떡볶이떡");
        list.add("굵게 다진 마늘");
        list.add("새송이");
        list.add("블루멜로우");
        list.add("탄산수");
        list.add("얼음");
        list.add("블루멜로우티");
        list.add("블루 큐라소");
        list.add("브리오슈 번");
        list.add("일레디젤라또 노블그린티");
        list.add("스노우빙 구슬인절미");
        list.add("맘스리얼베이스 고구마");
        list.add("팥");
        list.add("고구마 칩");
        list.add("소불고기감");
        list.add("천연조미료 해물육수");
        list.add("썬파");
        list.add("조미료(매운톡톡)");
        list.add("연겨자");
        list.add("대패 소고기");
        list.add("근대");
        list.add("백미");
        list.add("해물믹스");
        list.add("조미료(씨푸드빠에야시즈닝)");
        list.add("돼지뒷다리살");
        list.add("흰쌀밥");
        list.add("마파두부소스");
        list.add("우동면");
        list.add("대패삼겹 또는 우삼겹");
        list.add("케일");
        list.add("땅콩 소스");
        list.add("대패삼겹");
        list.add("매실액기스");
        list.add("채 썬 사과");
        list.add("통계피");
        list.add("레몬 즙");
        list.add("사골곰탕");
        list.add("청포묵");
        list.add("참나물");
        list.add("검은깨 또는 통깨");
        list.add("냉동만두");
        list.add("통마늘(큰것)");
        list.add("깻잎 작은것");
        list.add("작은 무");
        list.add("소양지");
        list.add("쌈무");
        list.add("소고기안심 또는 등심");
        list.add("표고버섯 또는 양송이");
        list.add("가래떡");
        list.add("땅콩분태");
        list.add("참치캔 작은거");
        list.add("훈제오리");
        list.add("참치 회");
        list.add("찬밥");
        list.add("초장");
        list.add("국산 유부 초밥");
        list.add("국산콩 두부");
        list.add("기름(현미유)");
        list.add("코코아 파우더");
        list.add("자색 고구마 가루");
        list.add("느타리버섯(고기)");
        list.add("곶감(건시)");
        list.add("후랑크 소세지");
        list.add("마");
        list.add("라면사리");
        list.add("떡사리");
        list.add("건미역");
        list.add("바지락살");
        list.add("조미료(연두 또는 다시다)");
        list.add("빵(호밀)");
        list.add("쌀국수");
        list.add("백설 베트남식 쌀국수소스");
        list.add("올리브 오일");
        list.add("대파썬것");
        list.add("메론");
        list.add("묵은김치");
        list.add("백년초가루");
        list.add("수삼 간것");
        list.add("잣가루");
        list.add("굴림 만두");
        list.add("말린 당근");
        list.add("말린 새송이버섯");
        list.add("파래(물)");
        list.add("사골육수");
        list.add("천사채");
        list.add("만든 양념장");
        list.add("꿀(동서벌꿀)");
        list.add("박력분(100g씩)");
        list.add("실온 우유(200ml씩)");
        list.add("실온계란");
        list.add("버터 30g씩");
        list.add("설탕 10g씩");
        list.add("베이킹파우더 6g씩");
        list.add("소금 2g씩");
        list.add("떡(절편)");
        list.add("쑥가루");
        list.add("시나몬가루");
        list.add("따뜻한우유");
        list.add("이스트");
        list.add("미지근한생 막걸리");
        list.add("손질한 고등어");
        list.add("고추냉이");
        list.add("탈피 들깨가루");
        list.add("시판 카레가루");
        list.add("냉동해물");
        list.add("소고기 꼬리");
        list.add("파슬리");
        list.add("쌀");
        list.add("송송 썬 달래");
        list.add("새우살");
        list.add("다시마멸치육수");
        list.add("돼지고기다짐육");
        list.add("닭안심");
        list.add("통후추");
        list.add("미지근한 물");
        list.add("드라이 이스트");
        list.add("다진 호두");
        list.add("조미료(보크라이스)");
        list.add("백태(흰 콩)");
        list.add("계란 전란");
        list.add("꿀 또는 물엿");
        list.add("다시 육수팩");
        list.add("청홍고추");
        list.add("침기름 또는 들기름");
        list.add("샌드위치햄");
        list.add("당근 라페");
        list.add("딸기쨈");
        list.add("오돌뼈");
        list.add("새우젓 건더기");
        list.add("새우젓국물");
        list.add("백 명란");
        list.add("계란후라이");
        list.add("조미김");
        list.add("전분");
        list.add("추가 밀가루");
        list.add("달걀 흰자");
        list.add("다진 돼지고기");
        list.add("물(끓는물 800 + 차가운 물 700ml)");
        list.add("검은깨 간 것");
        list.add("건표고버섯");
        list.add("국수");
        list.add("마른김");
        list.add("옥수수 콘");
        list.add("머스터드");
        list.add("우럭");
        list.add("쑥");
        list.add("양파 반");
        list.add("멸치(또는다시마)");
        list.add("닭고기안심 다짐육");
        list.add("다진사과");
        list.add("요거트(불가리스 or 비피더스)");
        list.add("녹두");
        list.add("인삼");
        list.add("편썬 인삼");
        list.add("귤 즙");
        list.add("흰 강낭콩 종이컵");
        list.add("묵은지(잎이 큰것으로)");
        list.add("굵은 고춧가루");
        list.add("돼지고기앞다리살 또는 뒷다리살");
        list.add("백설탕");
        list.add("우유 또는 계란");
        list.add("국산통밀 국수");
        list.add("얼그레이 티백");
        list.add("냉동 버터");
        list.add("닭볶음탕용 닭");
        list.add("고구마(작은사이즈)");
        list.add("차가운물");
        list.add("생닭");
        list.add("찹쌀");
        list.add("손질새우");
        list.add("육수(야채육수or멸치육수)");
        list.add("새우젓 또는 소금");
        list.add("간장(다시마간장)");
        list.add("병아리콩 밥");
        list.add("닭가슴살캔");
        list.add("웨지 감자");
        list.add("마늘 콩소스");
        list.add("간 소고기");
        list.add("볶음김치");
        list.add("다진양파 o.");
        list.add("퀵 오트밀");
        list.add("코코아가루(카카오 가루)");
        list.add("코코넛오일");
        list.add("코다리");
        list.add("알 도루묵");
        list.add("간생강");
        list.add("오만둥이");
        list.add("꽃 빵");
        list.add("과자(초코 다이제)");
        list.add("소고기등심 다짐육");
        list.add("돼지고기등심 다짐육");
        list.add("다진 대파 흰대");
        list.add("다진 홍고추");
        list.add("깻가루");
        list.add("호밀가루");
        list.add("미지근한물");
        list.add("호박고구마");
        list.add("토마토케첩 or 피자소스");
        list.add("갓");
        list.add("절임 소금");
        list.add("찹쌀풀용 물");
        list.add("찹쌀 풀용 찹쌀 가루");
        list.add("레드 와인");
        list.add("술을 짜낸 건과일 절임");
        list.add("어묵 볶음");
        list.add("계란 후라이");
        list.add("저염 명란");
        list.add("견과류(넛츠앤베리스 피칸 크랜베리 리얼믹스)");
        list.add("실온 달걀");
        list.add("화이트 초콜릿");
        list.add("실온 버터");
        list.add("갈색 설탕");
        list.add("녹차 파우더");
        list.add("등갈비");
        list.add("밤");
        list.add("삶은 물");
        list.add("월계수 잎");
        list.add("월남 고추");
        list.add("쇠고기");
        list.add("조갯살");
        list.add("청국장");
        list.add("집된장");
        list.add("오징어포");
        list.add("쌀조청");
        list.add("김장 양념장");
        list.add("흰 설탕");
        list.add("생 김");
        list.add("정육된 닭다리살");
        list.add("타임");
        list.add("바질");
        list.add("기름(닭을굽고남은기름)");
        list.add("화이트와인");
        list.add("슬라이스 햄");
        list.add("슬라이스 체다치즈");
        list.add("허니머스타드 소스");
        list.add("고구마전분");
        list.add("치자 가루");
        list.add("계란흰자");
        list.add("파 초록색부분");
        list.add("참치");
        list.add("김칫국물");
        list.add("오뚜기쉐이크앤팬 핫케이크믹스");
        list.add("아카시아 꿀");
        list.add("짜장(오뚜기)");
        list.add("굴 소스");
        list.add("아스파라거스");
        list.add("빨간파프리카");
        list.add("노란파프리카");
        list.add("알새우");
        list.add("샐러드채소");
        list.add("발사믹글레이즈");
        list.add("그라나파다노");
        list.add("건 다시마");
        list.add("멸치가루");
        list.add("사골국물");
        list.add("후르츠칵테일");
        list.add("갓김치");
        list.add("찐감자 주먹사이즈");
        list.add("남은불고기");
        list.add("모닝빵");
        list.add("떡(인절미)");
        list.add("아이스크림");
        list.add("어린잎");
        list.add("바게트빵");
        list.add("소고기사골");
        list.add("소고기사골(반골)");
        list.add("소고기사골(도가니)");
        list.add("카레 가루");
        list.add("굵은고춧가루");
        list.add("유자청");
        list.add("오렌지 주스");
        list.add("볼어묵");
        list.add("냉동모둠해물");
        list.add("냉동새우 대");
        list.add("냉동모둠 야채");
        list.add("고춧기름");
        list.add("노두유");
        list.add("짜장가루");
        list.add("면(짜장사리)");
        list.add("시판된장");
        list.add("참치캔 작은 것");
        list.add("무피클");
        list.add("삶은달걀");
        list.add("서리태콩");
        list.add("꿀 또는 조청(올리고당)");
        list.add("치킨스톡 파우더");
        list.add("다진김치");
        list.add("노바시 새우");
        list.add("배즙(도라지배즙)");
        list.add("끓인 밥 또는 찹쌀풀");
        list.add("참치액젓");
        list.add("다진 생강");
        list.add("자른 건미역");
        list.add("훈제닭가슴살");
        list.add("쥬키니호박");
        list.add("일반 우유");
        list.add("무가당 생크림");
        list.add("70% 이상 다크초콜릿");
        list.add("무가당 코코아파우더");
        list.add("캐소나드");
        list.add("50% 이상 다크초콜릿");
        list.add("납작어묵");
        list.add("고추가루 안매운것");
        list.add("고추가루 매운것");
        list.add("양념 소불고기");
        list.add("닭다리(북채)");
        list.add("양파 작은것");
        list.add("건다시마");
        list.add("고추씨");
        list.add("라이스앤화이버시리얼");
        list.add("사과주스");
        list.add("요플레(딸기요플레)");
        list.add("요구르트(사과요구르트)");
        list.add("유부 초밥 만들기세트");
        list.add("마늘 후레이크");
        list.add("아몬드분말");
        list.add("계란2개의 흰자");
        list.add("식용색소");
        list.add("계란4개의 노른자");
        list.add("치즈가루");
        list.add("쌀떡");
        list.add("통깨 또는 견과류");
        list.add("올리고당 또는 물엿");
        list.add("마늘쫑");
        list.add("사천 짜장분말");
        list.add("체리");
        list.add("옥수수전분");
        list.add("아몬드파우더");
        list.add("다크초콜릿");
        list.add("김장용 육수");
        list.add("엿기름 티백");
        list.add("저민생강");
        list.add("인스턴트 드라이이스트");
        list.add("녹인 버터");
        list.add("부대찌개라면");
        list.add("얼린 딸기");
        list.add("얼린 바나나");
        list.add("요거트파우더");
        list.add("시럽");
        list.add("백 진미채");
        list.add("냉동크로와상생지");
        list.add("복숭아(통조림)");
        list.add("고기");
        list.add("국물멸치");
        list.add("김밥용 햄");
        list.add("김밥용 우엉");
        list.add("매실엑기스");
        list.add("고둥(보말)");
        list.add("덧 된장");
        list.add("건고사리");
        list.add("표고버섯가루");
        list.add("피망(빨강)");
        list.add("피망(노랑)");
        list.add("피망(초록)");
        list.add("적양파");
        list.add("와사비");
        list.add("산야초효소 또는 생와사비딥소스");
        list.add("춘장");
        list.add("불린 고사리");
        list.add("라면");
        list.add("자숙문어 대가리");
        list.add("씻은 김치");
        list.add("동그랑땡");
        list.add("명란젓갈");
        list.add("곱게 갈은깨");
        list.add("식물성 오일");
        list.add("바닐라엑스트렉");
        list.add("스프링클");
        list.add("올방개묵");
        list.add("송송썬파");
        list.add("소고기차돌박이");
        list.add("다시마육수(다시마멸치육수)");
        list.add("소고기 볶음");
        list.add("연근 조림");
        list.add("김치(깍두기)");
        list.add("갈치 속젓");
        list.add("시판 사골곰탕");
        list.add("대파 반대");
        list.add("다시마육수 팩");
        list.add("구운 계란");
        list.add("곶감(말이)");
        list.add("대추(말이)");
        list.add("냉이 데친 것");
        list.add("바게트");
        list.add("머스타드 소스");
        list.add("굵은소금(오이절임용)");
        list.add("시금치 데친 것");
        list.add("대파 흰 부분");
        list.add("고사리");
        list.add("김장김치");
        list.add("닭날개");
        list.add("슬라이스햄(목우촌)");
        list.add("커피 에센스");
        list.add("깔루아");
        list.add("밀크 초콜릿");
        list.add("코팅용 밀크 초콜릿");
        list.add("통아몬드");
        list.add("가는소금");
        list.add("소고기불고기 또는 샤브용");
        list.add("만가닥버섯");
        list.add("계란 노른자");
        list.add("오리엔탈 소스");
        list.add("차가운 흰자");
        list.add("라면 수프");
        list.add("체다 슬라이스 치즈");
        list.add("양송이 버섯");
        list.add("새송이 버섯");
        list.add("표고 버섯");
        list.add("팽이 버섯");
        list.add("만가닥 버섯");
        list.add("양념 불고기");
        list.add("쪽파 다진것");
        list.add("실란트로(고수 또는 쑥갓)");
        list.add("백후추");
        list.add("옥수수가루");
        list.add("소사태");
        list.add("어묵 탕");
        list.add("히비스커스 분말");
        list.add("판젤라틴");
        list.add("채썬 양배추");
        list.add("다이제");
        list.add("사각 어묵");
        list.add("비엔나 소시지");
        list.add("숙성 배추김치");
        list.add("도톰한 동그랑땡");
        list.add("다진 견과류");
        list.add("햄통조림(K로스팜 큰캔)");
        list.add("당근 작은것");
        list.add("귀리 밥");
        list.add("슬라이드치즈");
        list.add("스팸 작은거");
        list.add("크랜베리");
        list.add("간 양파");
        list.add("칼국수면");
        list.add("국멸치");
        list.add("시나몬 가루");
        list.add("탈각 새우");
        list.add("소라");
        list.add("고사리 불린것");
        list.add("로메인상추");
        list.add("도토리묵");
        list.add("돼지고기삼겹살(통삼겹)");
        list.add("다진마");
        list.add("벌집 삼겹살");
        list.add("모차렐라치즈");
        list.add("멸치 또는 디포리");
        list.add("감자 작은 거");
        list.add("양파 큰거");
        list.add("카레 여왕");
        list.add("모듬 버섯");
        list.add("중력분 밀가루");
        list.add("양파가루");
        list.add("블루베리");
        list.add("말린사과(큐브)");
        list.add("실온 달걀노른자");
        list.add("생 닭가슴살");
        list.add("긴 새우");
        list.add("소고기 잡채용");
        list.add("냉채소스");
        list.add("고로케");
        list.add("작은당근");
        list.add("조미안된 카레가루");
        list.add("소고기채끝살");
        list.add("청고추");
        list.add("돼지고기뒷다리");
        list.add("설탕 작게");
        list.add("각종버섯");
        list.add("소고기(샤브용)");
        list.add("불고기용소고기");
        list.add("불고기 양념장");
        list.add("소금뿌린 생고등어 필렛");
        list.add("소고기 부채살");
        list.add("청양고추(장아찌)");
        list.add("생와사비");
        list.add("후랑크소시지");
        list.add("비엔나 소세지");
        list.add("새우젓 국물");
        list.add("들깨가루 크게");
        list.add("흑임자");
        list.add("시판 유부 초밥");
        list.add("시판 통통 완자");
        list.add("마른약 도라지");
        list.add("올리고당(프락토)");
        list.add("도라지 잔뿌리 크게");
        list.add("조청 쌀엿");
        list.add("레몬 제스트");
        list.add("틀에발라줄 버터");
        list.add("참치캔 작은것");
        list.add("소고기 국거리용");
        list.add("두부 부침용");
        list.add("곤약");
        list.add("소라 살");
        list.add("소라 내장");
        list.add("조기");
        list.add("명태머리");
        list.add("육수용멸치");
        list.add("혼다시");
        list.add("돼지고기 앞다리살");
        list.add("미니양배추");
        list.add("브로컬리 낱개로");
        list.add("홈플 해물믹스");
        list.add("작은 건새우");
        list.add("곡물식빵");
        list.add("삶은 계란");
        list.add("피클");
        list.add("돼지고기등뼈");
        list.add("할라피뇨");
        list.add("땡초");
        list.add("돈까스");
        list.add("양념장(만능 소스)");
        list.add("돼지고기 족발");
        list.add("돼지고기뒷다리살");
        list.add("깍두기 김치");
        list.add("깍두기 김치국물");
        list.add("소금(밑간용)");
        list.add("배추 속잎");
        list.add("파(4cm)");
        list.add("씻은 묵은김치");
        list.add("치킨 텐더");
        list.add("머스터드 소스");
        list.add("요거트 소스");
        list.add("플레인 요거트");
        list.add("오레가노");
        list.add("머위");
        list.add("고추장 넘치게");
        list.add("된장 넘치게");
        list.add("식용유(현미유)");
        list.add("하림 IFF 불 닭발 볶음");
        list.add("하림 IFF 닭똥집 볶음");
        list.add("김자반");
        list.add("뉴 슈가");
        list.add("표고");
        list.add("들기름 또는 참기름");
        list.add("생강청 건더기 다져서");
        list.add("소고기사태");
        list.add("오이고추");
        list.add("햄통조림");
        list.add("시판 토마토소스");
        list.add("튀김유");
        list.add("디포리");
        list.add("대파 한");
        list.add("자반고등어 필렛");
        list.add("찬물");
        list.add("반건조 홍합");
        list.add("오리훈제");
        list.add("멸치 육수");
        list.add("두유");
        list.add("마라샹궈 소스");
        list.add("굴소스 또는 마파소스");
        list.add("채끝살");
        list.add("올리브유(고기밑간)");
        list.add("소금(고기밑간)");
        list.add("후추(고기밑간)");
        list.add("머스트 소스");
        list.add("스테이크소스");
        list.add("대왕 조개");
        list.add("코끼리 조개");
        list.add("문어 해물탕밀키트");
        list.add("냉동 낙지");
        list.add("냉동 오징어");
        list.add("만능양념장");
        list.add("데친 새우");
        list.add("조미료");
        list.add("사각 라이스페이퍼");
        list.add("끓는물");
        list.add("팔도 비빔면");
        list.add("라이스페이퍼");
        list.add("자숙새우");
        list.add("파인애플");
        list.add("돼지고기 뒷다리살");
        list.add("식초(쌀식초)");
        list.add("샤브용 소고기");
        list.add("쌈 다시마");
        list.add("홍파프리카");
        list.add("옐로우 파프리카");
        list.add("소라(손질된 것)");
        list.add("채썬대파");
        list.add("멸치(다시팩)");
        list.add("중국 당면");
        list.add("떡볶이용 떡");
        list.add("머쉬마루 버섯");
        list.add("잔멸치");
        list.add("데리야키소스");
        list.add("이탈리안시즈닝");
        list.add("물 한컵");
        list.add("국거리소고기");
        list.add("신라면");
        list.add("칵테일 새우");
        list.add("파르메산치즈가루");
        list.add("취나물");
        list.add("콜라 또는 사이다");
        list.add("옥수수콘");
        list.add("메주콩");
        list.add("쌀뜬물");
        list.add("땅콩");
        list.add("소고기(불고기거리)");
        list.add("불고기 양념");
        list.add("와사비 or 연겨자");
        list.add("비비고 사골곰탕");
        list.add("돈까스(등심)");
        list.add("얌랩건조마시멜로우멜로팝레인보우");
        list.add("흰우유");
        list.add("우유");
        list.add("초코우유");
        list.add("후르츠링");
        list.add("첵스초코");
        list.add("콘푸라이트");
        list.add("초당 순두부");
        list.add("멸치다시마 육수");
        list.add("피스타치오");
        list.add("캐슈넛");
        list.add("익은 김치");
        list.add("1cm 두께로 통썰기한 무");
        list.add("녹두 간것");
        list.add("돼지고기 간거(앞다리살)");
        list.add("대파(쪽파)");
        list.add("방풍나물");
        list.add("계피");
        list.add("다진청양고추");
        list.add("매생이(1/2재기)");
        list.add("육수 다시팩");
        list.add("무청(또는 열무)");
        list.add("이쑤시개");
        list.add("건 당면");
        list.add("만두피(냉동만두피)");
        list.add("전복");
        list.add("얇게 썬 마늘");
        list.add("통조림 꽁치");
        list.add("레몬즙(식초)");
        list.add("손질 주꾸미");
        list.add("노지 시금치");
        list.add("포항초)");
        list.add("깐 도라지");
        list.add("삶은 고사리");
        list.add("다진마늘 1티스푼씩");
        list.add("곱게갈은 깨");
        list.add("도토리가루");
        list.add("요리 당");
        list.add("생미역");
        list.add("버터치킨(시판)");
        list.add("모짜렐라치즈(치즈커드)");
        list.add("흰다리새우");
        list.add("굵은 고추가루");
        list.add("파인애플 통조림");
        list.add("스윗 칠리소스");
        list.add("피클 머스타드소스");
        list.add("생 가자미");
        list.add("볶은참깨");
        list.add("편으로 썬 마늘");
        list.add("호박씨");
        list.add("중멸치");
        list.add("메추리알");
        list.add("데친숙주");
        list.add("포기김치");
        list.add("다진소고기");
        list.add("레드와인");
        list.add("천연조미료해물 육수");
        list.add("씻은김치");
        list.add("커버춰 다크초콜릿");
        list.add("홍차 티백");
        list.add("비엔나소시지");
        list.add("노란 파프리카");
        list.add("멸치(육수용)");
        list.add("다시마(육수용)");
        list.add("파뿌리(육수용)");
        list.add("무(육수용)");
        list.add("국수소면");
        list.add("참기름 한");
        list.add("두부(150g)");
        list.add("잔파");
        list.add("부침가루 종이컵");
        list.add("물 종이컵");
        list.add("진 간장");
        list.add("말린고사리");
        list.add("몰트가루");
        list.add("발효종");
        list.add("원당");
        list.add("현미유");
        list.add("으깬 감자");
        list.add("메이플시럽");
        list.add("로즈메리");
        list.add("소고기 업진살");
        list.add("오꼬노미야끼소스");
        list.add("잔멸치 냉면기");
        list.add("우유식빵");
        list.add("마요네즈(청양고추맛)");
        list.add("바베큐소스");
        list.add("홍합(24cm곰솥)");
        list.add("물(24cm곰솥)");
        list.add("만개한알");
        list.add("황태포");
        list.add("녹말물");
        list.add("황태머리");
        list.add("육수(밑국물)");
        list.add("소고기양지(양지사태)");
        list.add("다진 양파");
        list.add("다진 당근");
        list.add("자른 김");
        list.add("대게 킹크랩");
        list.add("날치알");
        list.add("두부 반모");
        list.add("어묵 4장");
        list.add("멸치 종이컵");
        list.add("홍청양고추");
        list.add("채소(채썬것)");
        list.add("오징어(500g)");
        list.add("전분가루(또는밀가루)");
        list.add("소금 밥숟가락");
        list.add("다진마늘 밥숟가락");
        list.add("식빵(짜투리)");
        list.add("베트남 고추");
        list.add("된장 크게");
        list.add("감자 튀김(냉동)");
        list.add("흰 우유");
        list.add("바질페스토");
        list.add("토마토(선드라이드토마토)");
        list.add("치즈(슬라이스or피자치즈 등)");
        list.add("올리고당(꿀or메이플시럽)");
        list.add("검정깨");
        list.add("건홍합");
        list.add("육수팩(다시팩)");
        list.add("생콩가루");
        list.add("닭발");
        list.add("갈은 파래 김");
        list.add("소고기(삶은것)");
        list.add("건새우가루");
        list.add("소고기등심");
        list.add("양쪽이 삐죽한 이쑤시개");
        list.add("야채(냉동모둠야채)");
        list.add("김치 톡톡");
        list.add("트러플 오일");
        list.add("파에테포요틴");
        list.add("화이트초콜릿");
        list.add("딸기 파우더");
        list.add("휘핑된 생크림");
        list.add("타르트틀");
        list.add("묵은지 반포기");
        list.add("물(1200ml)");
        list.add("돼지고기(먹다 남은 양)");
        list.add("면수");
        list.add("호박 고구마");
        list.add("양파작은것");
        list.add("건크렌베리");
        list.add("갈아만든배 또는 배 갈은것");
        list.add("위생봉지");
        list.add("숙주나물(1봉)");
        list.add("겨자가루");
        list.add("빻은 통깨");
        list.add("다진 파");
        list.add("키위(간 것)");
        list.add("깐 밤");
        list.add("갈아 만든 배 음료");
        list.add("계란 지단");
        list.add("섬초");
        list.add("표고버섯 칩");
        list.add("연두청양초");
        list.add("참치캔 큰사이즈");
        list.add("동태살");
        list.add("간장(게간장)");
        list.add("갈비양념소스(시판용)");
        list.add("볶음깨");
        list.add("간 마늘");
        list.add("다시마 가루");
        list.add("건 표고버섯");
        list.add("집간장");
        list.add("황태 포");
        list.add("소금 1큰술+");
        list.add("소고기우둔살");
        list.add("감자 전분 소복이");
        list.add("김 가루");
        list.add("참기름 깨소금");
        list.add("깨소금 후추");
        list.add("스팸(클래식)");
        list.add("물만두");
        list.add("그라노파다노 치즈");
        list.add("넛맥");
        list.add("코팅 다크초콜릿");
        list.add("김치만두");
        list.add("계란 지단고명");
        list.add("다시육수 종이컵");
        list.add("스파게티면 원하는");
        list.add("브라운슈거");

    }
}